### ISSUE TITLE
Bug: Fails to build rules_ios library target in BwB

### ISSUE THREAD

**Issue by luispadron** [MobileNativeFoundation/rules_xcodeproj#1929] opened 2023-03-29 21:18 UTC
### What happened?

Generated a `rules_ios` based project with `BwB` and the `all` generation scheme mode.
When building the "yellow" library targets in Xcode that are generated we received a run script error:

```
CompileC /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/Objects-normal/arm64/_CompileStub_.o /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/DerivedSources/_CompileStub_.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'SwiftFramework' from project 'Project')
    cd /var/tmp/_bazel_lpadron/e26c4188e56823b3c8e12b2563cf675b/rules_xcodeproj/build_output_base/execroot/rules_xcodeproj_playground
    /Users/lpadron/Development/rules_xcodeproj_playground/Project.xcodeproj/rules_xcodeproj/bazel/clang.sh -x objective-c -target arm64-apple-ios14.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-implicit-fallthrough -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version\=2 -fobjc-legacy-dispatch -MMD -MT dependencies -MF /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/Objects-normal/arm64/_CompileStub_.d --serialize-diagnostics /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/Objects-normal/arm64/_CompileStub_.dia -c /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/DerivedSources/_CompileStub_.m -o /Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/Objects-normal/arm64/_CompileStub_.o

error: Build input file cannot be found: '/Users/lpadron/Library/Developer/Xcode/DerivedData/Project-dxupostqumucsycroidgkcqwpevd/Build/Intermediates.noindex/Project.build/bazel-out/ios-sim_arm64-min14.0-applebin_ios-ios_sim_arm64-dbg-ST-839cdaff2330/bin/SwiftFramework/SwiftFramework/DerivedSources/_CompileStub_.m'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'SwiftFramework' from project 'Project')
```

### Reproduction steps

- Download the zipped repro project
- Run `bazel run //:Project && xed Project.xcodeproj`
- Build the <img width="122" alt="Screenshot 2023-03-29 at 5 17 31 PM" src="https://user-images.githubusercontent.com/13840545/228669807-24513ac0-3ea5-4073-80a7-2882e5f0bf07.png"> target
- See error

### Expected behavior

We expect all generated schemes/targets to be buildable without errors.

### rules_xcodeproj version

047775d86a0db85e821bbbe1bd4d5ca1cba8fabc

### Bazel version

6.0.0

### rules_apple version

2fb221631dec5dfbbe650bd8a614237eb46cb7db

### rules_swift version

(from rules_apple)

### Additional information

Reproduction project:
[rules_xcodeproj_compile_stub_repro.zip](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/11105577/rules_xcodeproj_compile_stub_repro.zip)

Additionally, you can reproduce live at: https://github.com/mattrobmattrob/rules_xcodeproj_playground/tree/mr/rules_ios.swift.fwk with the only change being to modify `helpers.bzl` to use `all` generation mode.

**Comment by brentleyjones** [comment] 2023-03-29 22:47
Turns out this is a duplicate of https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1718. The issue here is that we don't have link params, because we need to collect flags from the archive step and set that for `OTHER_LIBTOOLFLAGS` instead. I'll see if I can tackle this next week.

**Comment by luispadron** [comment] 2023-03-30 14:51
Ah gotcha, thanks! Feel free to close this if you prefer to track it in the other issues.

**Comment by brentleyjones** [comment] 2023-03-30 14:54
This is a good repro, so I'll leave it open.

**Comment by brentleyjones** [comment] 2023-03-30 17:38
It's actually slightly different than #105, because of the `PackagingFrameworkBinary` action. I think the improved target merging might be the real solution for this specific issue.

**Comment by brentleyjones** [comment] 2023-11-29 16:42
@luispadron is this addressed with incremental generation?

**Comment by luispadron** [comment] 2023-11-29 16:51
Yes it is!

**Closed** 2023-12-19 17:02 UTC
Labels: bug, 3rd party rules
