### ISSUE TITLE
Bug: rules_ios lldb issue with generated Swift headers

### ISSUE THREAD

**Issue by mattrobmattrob** [MobileNativeFoundation/rules_xcodeproj#2201] opened 2023-05-16 16:33 UTC
### Description

lldb has problems with visibility of generated header defined `@objc` values for use in Objective-C headers. This can be sidestepped by running a RegEx replacement of:
```
-ivfsoverlay\$\(CURRENT_EXECUTION_ROOT\)/([a-zA-Z\-/_0-9\.]*)/([a-z]*)_swift_vfs\.yaml
```
With:
```
 -ivfsoverlay$(CURRENT_EXECUTION_ROOT)/$1/$2_swift_vfs.yaml - ivfsoverlay$(CURRENT_EXECUTION_ROOT)/$1/$2_vfs.yaml
```
In the `examples/rules_ios/rules_ios.xcodeproj/bazel/Debug-swift_debug_settings.py` file seemingly indicating an issue with picking up the `ivfsoverlay` copts that aren't present in the `swift_library` target in the rules_ios target cluster.

An example vfs copt is `//iOSApp/Source/Utils:Utils_vfs` that's present on `//iOSApp/Source/Utils:Utils_objc`:
```
$ bazel query --output=build //iOSApp/Source/Utils:Utils_objc
# /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/iOSApp/Source/Utils/BUILD:6:26
objc_library(
  name = "Utils_objc",
  tags = ["manual"],
  generator_name = "Utils",
  generator_function = "apple_framework",
  generator_location = "iOSApp/Source/Utils/BUILD:6:26",
  testonly = False,
  features = [],
  data = ["//iOSApp/Source/Utils:Utils_wrapped_resources_filegroup"],
  srcs = ["//iOSApp/Source/Utils:Foo.m"],
  non_arc_srcs = [],
  pch = "@build_bazel_rules_ios//rules/library:common.pch",
  defines = [],
  module_map = "//iOSApp/Source/Utils:Utils-modulemap/Utils.modulemap",
  hdrs = ["//iOSApp/Source/Utils:Foo.h", "//iOSApp/Source/Utils:Utils.h", "//iOSApp/Source/Utils:Utils-modulemap/Utils-umbrella.h", "//iOSApp/Source/Utils:Utils-modulemap/Utils.modulemap"],
  sdk_includes = [],
  deps = ["//iOSApp/Source/CoreUtilsObjC:CoreUtilsObjC", "//iOSApp/Source/UtilsSwift:UtilsSwift", "//iOSApp/Source/Utils:Utils_public_hmap"] + select({"@build_bazel_rules_ios//:virtualize_frameworks": ["//iOSApp/Source/Utils:Utils_swift_vfs", "//iOSApp/Source/Utils:Utils_vfs"], "//conditions:default": ["//iOSApp/Source/Utils:Utils_swift_vfs", "//iOSApp/Source/Utils:Utils_vfs"]}),
  sdk_frameworks = [],
  weak_sdk_frameworks = [],
  sdk_dylibs = [],
  copts = [] + [] + select({"@build_bazel_rules_ios//:virtualize_frameworks": ["-ivfsoverlay$(execpath :Utils_vfs)", "-F/build_bazel_rules_ios/frameworks"], "//conditions:default": ["-ivfsoverlay$(execpath :Utils_vfs)", "-F/build_bazel_rules_ios/frameworks"]}) + ["-I$(execpath :Utils_public_hmap)", "-fmodules", "-fmodule-name=Source_Utils", "-I."] + select({"@build_bazel_rules_ios//:use_global_index_store": ["-index-store-path", "bazel-out/_global_index_store"], "//conditions:default": ["-index-store-path", "$(GENDIR)/iOSApp/Source/Utils/rules_ios_objc_library_Utils_objc.indexstore"]}),
)
# Rule Utils_objc instantiated at (most recent call last):
#   /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/iOSApp/Source/Utils/BUILD:6:26                                             in <toplevel>
#   /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/external/build_bazel_rules_ios/rules/framework.bzl:97:28 in apple_framework
#   /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/external/build_bazel_rules_ios/rules/library.bzl:1039:24 in apple_library
# Rule objc_library defined at (most recent call last):
#   /virtual_builtins_bzl/common/objc/objc_library.bzl:87:20 in <toplevel>
```

### Reproduction steps

Branch: https://github.com/mattrobmattrob/rules_xcodeproj/tree/mr/rules_ios/lldb.issue.in.tests
Comparison: https://github.com/MobileNativeFoundation/rules_xcodeproj/compare/main...mattrobmattrob:rules_xcodeproj:mr/rules_ios/lldb.issue.in.tests?expand=1

1. `cd examples/rules_ios && bazel run :xcodeproj`
2. `open rules_ios.xcodeproj`
3. Select `iOSAppMixedUnitTests` scheme.
4. Drop breakpoint in `SwiftUnitTests.swift::8` and run `SwiftUnitTests.testExample`
5. `po self`

### Expected behavior

Expected:
```
Test Suite 'Selected tests' started at 2023-05-16 11:26:42.212
Test Suite 'iOSAppMixedUnitTests.xctest' started at 2023-05-16 11:26:42.212
Test Suite 'SwiftUnitTests' started at 2023-05-16 11:26:42.212
Test Case '-[iOSAppMixedUnitTests.SwiftUnitTests testExample]' started.
(lldb) po self
-[SwiftUnitTests testExample]
```

Demonstrated:
```
Test Suite 'Selected tests' started at 2023-05-16 11:21:35.141
Test Suite 'iOSAppMixedUnitTests.xctest' started at 2023-05-16 11:21:35.142
Test Suite 'SwiftUnitTests' started at 2023-05-16 11:21:35.142
Test Case '-[iOSAppMixedUnitTests.SwiftUnitTests testExample]' started.
(lldb) po self
error: expression failed to parse:
unknown error
(lldb) po self
warning: Swift error in scratch context: /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/iOSApp/Source/Utils/Foo.h:4:9: note: while building module 'Source_UtilsSwift' imported from /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/iOSApp/Source/Utils/Foo.h:4:
@import Source_UtilsSwift;
        ^

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/UtilsSwift-umbrella.h"
        ^

warning: /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-d98dbd8343b5/bin/iOSApp/Source/UtilsSwift/UtilsSwift-modulemap/UtilsSwift-umbrella.h:19:1: warning: umbrella header for module 'Source_UtilsSwift' does not include header 'Source_UtilsSwift-Swift.h'

^

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Utils-umbrella.h"
        ^

/Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-d98dbd8343b5/bin/iOSApp/Source/Utils/Utils-modulemap/Utils-umbrella.h:16:9: note: in file included from /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-d98dbd8343b5/bin/iOSApp/Source/Utils/Utils-modulemap/Utils-umbrella.h:16:
#import "Foo.h"
        ^

error: /Users/matt.robinson/Developer/github/buildbuddy-io/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/build_output_base/execroot/__main__/iOSApp/Source/Utils/Foo.h:11:31: error: no type or protocol named 'FileManagerProtocol'
- (void)handleFileManager:(id<FileManagerProtocol>)fileManager;
                              ^

error: could not build Objective-C module 'Source_Utils'
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/Utils-umbrella.h"
        ^

.
Shared Swift state for iOSApp_ExecutableName has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.

error: expression failed to parse:
unknown error
```

### rules_xcodeproj version

5195826c267fb9b5b14e4481a14a3e90231fa0ce

### Xcode version

14.3

### Bazel version

6.2.0

**Comment by brentleyjones** [comment] 2023-05-16 18:24
The way clang opts are collected, both how Xcode does it, and how we do it manually with `swift_debug_settings.py`, is by transitively picking up `-Xcc` flags on swift dependencies. If a dependent `swift_library` doesn't set this needed `-Xcc -ivfsoverlay`, then we won't see it, and lldb will be broken. We can't look at the copts of non swift dependencies. So to fix this, a `swift_library` that depends on `Utils_objc` would need to set `copts =  ["-Xcc" "-ivfsoverlay$(execpath :Utils_vfs)"]`.

**Comment by brentleyjones** [comment] 2023-05-16 18:26
The fact that this compiles though, and only errors in lldb, is concerning. That would indicate to me that we aren't picking up _something_ correctly, because otherwise normal compilation of `iOSApp_ExecutableName` should fail with the errors you are seeing.

**Comment by mattrobmattrob** [comment] 2023-05-16 20:03
My _bet_ is that it's related to the handling of the `apple_framework_packaging` (`non_xcode_targets`) rule in rules_ios that's just the odd exporter of providers compared to the "normal" `swift_library` => `objc_library` sandwich (like in `experimental_mixed_language_library`). But will try to confirm that explicitly tomorrow.

**Comment by mattrobmattrob** [comment] 2023-05-18 20:12
I'm hacking in a fix for this right now until I can get a real solution, it's just running this on the generated `{config}-swift_debug_settings.py`:
```
$ sed -i '' \
    's/_swift_vfs.yaml/_vfs.yaml/g' \
    'path/to/xcode/Project.xcodeproj/rules_xcodeproj/bazel/Debug-swift_debug_settings.py'
```

**Comment by thiagohmcruz** [comment] 2023-05-29 13:46
Just one other data point here. We're hitting a very similar err when stopping at a breakpoint in a test and trying to `po`, similar err msg mentioning a`-umbrella.h` file.

Doing the `sed` cmd above makes `po` work but auto-complete continues to be broken in the Xcode console, e.g. this shows "No Completions": `po foo.<press ESC to show list of options>`

**Comment by thiagohmcruz** [comment] 2023-05-29 17:47
> Just one other data point here. We're hitting a very similar err when stopping at a breakpoint in a test and trying to `po`, similar err msg mentioning a`-umbrella.h` file.
> 
> Doing the `sed` cmd above makes `po` work but auto-complete continues to be broken in the Xcode console, e.g. this shows "No Completions": `po foo.<press ESC to show list of options>`

The auto-complete issue is most likely unrelated to this issue, I fixed that by adding the two lines below [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/xcodeproj/internal/bazel_integration_files/generate_index_build_bazel_dependencies.sh#L11):
```sh
  "bi $BAZEL_TARGET_ID"
  "bp $BAZEL_TARGET_ID"
```
Will see if I can find a small repro since it's happened internally file a separate issue to track.

**Comment by brentleyjones** [comment] 2023-05-30 14:06
`bi` shouldn't be needed, it just creates the file that says where to find unit files to import.

`bp` is interesting. I think it has a side effect of causing some intermediate targets to be compiled/downloaded, which makes me think it's #2023.

**Comment by thiagohmcruz** [comment] 2023-05-30 14:24
> `bi` shouldn't be needed, it just creates the file that says where to find unit files to import.
> 
> `bp` is interesting. I think it has a side effect of causing some intermediate targets to be compiled/downloaded, which makes me think it's #2023.

Yep, confirmed that if I remove `bi` it continues to work for me, so yeah it's `bp` that's fixed it. Will take a look at the linked PR. With the `sed` in this issue and the `bi` line all our internal test cases that cover the common developer workflows involving LLDB are 🟢 btw 🎉.

**Comment by mattrobmattrob** [comment] 2023-11-14 18:49
Nope, @thiagohmcruz, haven't tried with the incremental generator. Happy to close this if the repro is fixed though!

**Comment by brentleyjones** [comment] 2023-11-14 18:50
If it's fixed with the new generation mode, let's leave it open until it's in `main` (when https://github.com/MobileNativeFoundation/rules_xcodeproj/milestone/42 is closed).

**Closed** 2023-12-19 17:01 UTC
Labels: bug, 3rd party rules
